=== Raja-AR-007/XML-Extensible-Markup-Language-/humansSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" 
targetNamespace="http://www.example.org/humansSchema" 
xmlns:tns="http://www.example.org/humansSchema" 
elementFormDefault="qualified">

<complexType name="humanstype">
	<sequence>
		<element name="human" type="tns:humantype" maxOccurs="3" minOccurs="1"></element>
	</sequence>
</complexType>

<complexType name="humantype">
	<sequence>
		<element name="name" type="string"></element>
		<element name="salary" type="tns:mySal"></element>
	</sequence>
	<attribute name="hid" type="ID" use="required"></attribute>
</complexType>

	<element name="globalhumans" type="tns:humanstype"/>
	
<simpleType name="mySal">
	<restriction base="integer">
		<minInclusive value='1000'></minInclusive>
		<maxInclusive value='10000'></maxInclusive>
	</restriction>
</simpleType>
</schema>

=== Raja-AR-007/XML-Extensible-Markup-Language-/newhumans.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:globalhumans xmlns:tns="http://www.example.org/humansSchema" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:schemaLocation="http://www.example.org/humansSchema humansSchema.xsd ">
  <tns:human hid="A1">
    <tns:name>Raja</tns:name>
    <tns:salary>30000</tns:salary>
  </tns:human>
  <tns:human hid="A2">
    <tns:name>David</tns:name>
    <tns:salary>2000</tns:salary>
  </tns:human>
  <tns:human hid="A3">
    <tns:name>Tom</tns:name>
    <tns:salary>4000</tns:salary>
  </tns:human>
  <tns:human hid="A4">
    <tns:name>Sam</tns:name>
    <tns:salary>6000</tns:salary>
  </tns:human>
</tns:globalhumans>
